name: Compatibility E2E
on:
  workflow_dispatch:
    inputs:
      release-branch:
        description: 'Release branch to test'
        required: true
        type: choice
        options:
          - release/v5.0.x
          - release/v6.0.x

env:
  REGISTRY: ghcr.io
  ORG: cosmos
  IMAGE_NAME: ibc-go-simd
  RELEASE_BRANCH: '${{ inputs.release-branch }}'

jobs:
  determine-docker-tag:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.set-docker-tag.outputs.docker-tag }}
    steps:
      - run: |
          docker_tag="$(echo $RELEASE_BRANCH | sed 's/\//-/')"
          echo $docker_tag
          echo "::set-output name=docker-tag::$docker_tag"
        id: set-docker-tag

  build-release-image:
    runs-on: ubuntu-latest
    needs: determine-docker-tag
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ env.RELEASE_BRANCH }}"
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch latest Dockerfile
        run: curl https://raw.githubusercontent.com/cosmos/ibc-go/main/Dockerfile -o Dockerfile
      - name: Build image
        run: |
          docker build . -t "${REGISTRY}/${ORG}/${IMAGE_NAME}:${{ needs.determine-docker-tag.outputs.docker-tag }}"
          docker push "${REGISTRY}/${ORG}/${IMAGE_NAME}:${{ needs.determine-docker-tag.outputs.docker-tag }}"

  transfer:
    needs:
      - build-release-image
      - determine-docker-tag
    uses: ./.github/workflows/e2e-compatibility-workflow-call.yaml
    with:
      docker-tag: "${{ needs.determine-docker-tag.outputs.docker-tag }}"
      test-suite: "transfer"

  client:
    needs:
      - build-release-image
      - determine-docker-tag
    uses: ./.github/workflows/e2e-compatibility-workflow-call.yaml
    with:
      docker-tag: "${{ needs.determine-docker-tag.outputs.docker-tag }}"
      test-suite: "client"

  incentivized-transfer:
    needs:
      - build-release-image
      - determine-docker-tag
    uses: ./.github/workflows/e2e-compatibility-workflow-call.yaml
    with:
      docker-tag: "${{ needs.determine-docker-tag.outputs.docker-tag }}"
      test-suite: "incentivized-transfer"
